project:
  type: book
  output-dir: _site

book:
  title: "Foundations of Vision (1995)"
  author: "Brian Wandell"
  date: "10/26/1995"
  chapters:
    - index.qmd
    - part: "Image Encoding"
      chapters:
       - part-1-image-encoding.qmd
       - chapter-2-image-formation.qmd
       - chapter-3-the-photoreceptor-mosaic.qmd
       - chapter-4-wavelength-encoding.qmd
    - part:  "Image Representation"
      chapters:
      - part-2-image-representation.qmd
      - chapter-5-the-retinal-representation.qmd
      - chapter-6-the-cortical-representation.qmd
      - chapter-7-pattern-sensitivity.qmd
      - chapter-8-multiresolution-image-representations.qmd
    - part: "Image Interpretation"
      chapters:
       - part-3-image-interpretation.qmd
       - chapter-9-color.qmd
       - chapter-10-motion-and-depth.qmd
       - chapter-11-seeing.qmd
    - references.qmd
    - part: "Appendix"
      chapters:
      - appendix.qmd
      - numbers.qmd
      - online-teaching-resources.qmd

bibliography: paperpile.bib

website:
  title: "Foundations of Vision (1995)"
  site-url: https://wandell.github.io/FOV-1995/
  repo-url: https://github.com/wandell/FOV-1995
  repo-actions: [edit, issue]

crossref:
  chapters: true
  fig-prefix: "Figure"
  tbl-prefix: "Table"
  sec-prefix: "Section"
  
#  I am unsure about these formatting commands for the document.  Experimental.
#     To remove tooltips for sec-*, we are supposed to be able to use this.
#     include-after-body: styles/disable-section-tooltips.js

format:
  html:
    csl:  styles/springer-basic-author-date.csl
    theme: cosmo
    number-sections: true
    number-depth: 2
    math:
      number-equations: true

  pdf:
    documentclass: scrreprt
    toc: true
    toc-title: "Contents"
    number-sections: true
    number-depth: 2
    fig-caption: true
    keep-tex: true
    csl:  styles/springer-basic-author-date.csl
    math:
      number-equations: true




